spring.application.name=authorization-service-java

spring.datasource.url=jdbc:postgresql://localhost:5433/cards
spring.datasource.username=postgres
spring.datasource.password=postgres

server.port=8081
