spring.application.name=authorization-service-java

spring.datasource.url=jdbc:postgresql://localhost:5433/cards
spring.datasource.username=postgres
spring.datasource.password=postgres

server.port=8081

kafka.bootstrap-servers=localhost:9092
kafka.topic=card.transactions
